language: c
dist: xenial

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - build-essential gcc-6
      env:
        - MATRIX_EVAL="CC=gcc-6"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - build-essential gcc-7
      env:
        - MATRIX_EVAL="CC=gcc-7"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - build-essential gcc-8
      env:
        - MATRIX_EVAL="CC=gcc-8"

before_install:
  - apt-get update
  - apt-get install -y autoconf autotools-dev libtool libsnmp-dev libattr1-dev libssl1.0.0
  - wget http://ftp.software.ibm.com/storage/tivoli-storage-management/maintenance/client/v7r1/Linux/LinuxX86_DEB/BA/v716/7.1.6.0-TIV-TSMBAC-LinuxX86_DEB.tar
  - tar xf 7.1.6.0-TIV-TSMBAC-LinuxX86_DEB.tar
  - dpkg -i gskssl64_8.0-50.66.linux.x86_64.deb
  - dpkg -i gskcrypt64_8.0-50.66.linux.x86_64.deb
  - dpkg -i tivsm-api64.amd64.deb
  - wget https://github.com/tstibor/ltsm.github.io/raw/master/lustre/lustre-builds/buster/client/2.13/lustre-client-utils_2.13.56-63-gde8ed5f-1_amd64.deb
  - wget https://github.com/tstibor/ltsm.github.io/raw/master/lustre/lustre-builds/buster/client/2.13/lustre-dev_2.13.56-63-gde8ed5f-1_amd64.deb
  - dpkg -i lustre-client-utils_2.13.56-63-gde8ed5f-1_amd64.deb
  - dpkg -i lustre-dev_2.13.56-63-gde8ed5f-1_amd64.deb
  - eval "${MATRIX_EVAL}"

script: ./autogen.sh && ./configure --enable-tests && make && ./src/test/test_cds && ./src/test/test_tsmapi
