# Automatically added by dh_installinit
if [ -x "/etc/init.d/fsqd" ]; then
	update-rc.d fsqd defaults >/dev/null
	invoke-rc.d fsqd start || exit $?
fi
# End automatically added section
# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
	deb-systemd-invoke start fsqd.service >/dev/null || true
fi
# End automatically added section
