# Automatically added by dh_installinit
if [ -x "/etc/init.d/lhsmtool_tsm" ]; then
	update-rc.d lhsmtool_tsm defaults >/dev/null
	invoke-rc.d lhsmtool_tsm start || exit $?
fi
# End automatically added section
# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
	deb-systemd-invoke start lhsmtool_tsm.service >/dev/null || true
fi
# End automatically added section
