.\" Copyright (c) 2017, Jörg Behrendt
.\"
.\" %%%LICENSE_START(GPLv2+_DOC_FULL)
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, see
.\" <http://www.gnu.org/licenses/>.
.\" %%%LICENSE_END

.TH "ltsmc" "1" "26.February 2017" "Thomas Stibor <t.stibor@gsi.de>, Jörg Behrendt <j.behrendt@gsi.de>" "version 0.2.0"

.SH NAME
ltsmc is a console client for archiving, retrieving, deleting and querying files and directories on a TSM server

.SH SYNOPSIS
ltsmc MODE OPTION... PATH

.SH DESCRIPTION
.SS
.BR MODES:
.TP
.BR \-\-archive
Archive files and directories on TSM server.
.TP
.BR \-\-query
Query TSM server for files and directories and print the result.
.TP
.BR \-\-retrieve
Query TSM server for files and directories, and retrieve matched files and directories for storing them locally.
.TP
.BR \-\-delete
Query TSM server for files and directories, and delete matched files and directories on the TSM server.
.SS
.BR OPTIONS:
Mandatory arguments to long options are mandatory for short options too except for verbose option.
.PP
REQUIRED
.TP
.BR \-n ", " \-\-node =\fINAME\fR
The name of the TSM node which is registered on the TSM server.
.TP
.BR \-p ", " \-\-password =\fIPASSWORD\fR
The password of the TSM node which is registered on the TSM server.
.TP
.BR \-s ", " \-\-servername =\fINAME\fR
The TSM servername to connect to. Name will be resolved to an actual ip address within the dsm.sys file.
.PP
OPTIONAL
.TP
.BR \-r ", " \-\-recursive
Archive directory recursively by also processing each sub-directory.
.TP
.BR \-l ", " \-\-latest
Query, restore and delete action will only select the latest version of the stored objects.
.TP
.BR \-f ", " \-\-fsname =\fIPATH\fR
TSM filespace name used for archiving, retrieving, querying and deleting, default is '/'. Note the filespace name must start with character '/'.
.TP
.BR \-d ", " \-\-description =\fISTRING\fR
If in archive mode the description will be stored in association with the TSM objects onto the TSM server. By default an empty string is used.
Otherwise the description will be used to select only the query results matching the description before continuing with the actual action and can contain the wildcards '*' or '?'. By default any description '*' will be selected.
.TP
.BR \-o ", " \-\-owner =\fINAME\fR
If in archive mode the owner's name  will be stored with the file objects onto the TSM server. By default an empty string is used.
Otherwise the name will be used to filter the queries by owner and the wildcards '*' or '?' are allowed. By default all owners will be selected.
.TP
.BR \-v ", " \-\-verbose =\fIerror\fR|\fIwarn\fR|\fImessage\fR|\fIinfo\fR|\fIdebug\fR
Causes ltsmc to be more verbose in printing messages. Default is \fImessage\fR.
.TP
.BR \-h ", " \-\-help
Display help and exit.
.SS
.BR PATH:
.PP
If not in archive mode a TSM object description is expected. The description is split into the low-level (ll) name which reflects the actual file name and a high-level (hl) name which reflects the path.
This split will occur at the last occurency of the path seperator '/' in the string. In addition wildcard characters '*' and '?' can be used to match multiple TSM objects, e.g.:
.TP
PATH='*'
hl='/' and ll='*' \- matches any file in path '/'
.TP
PATH='*/*'
hl='*' and ll='/*' \- matches any file in any path
.TP
PATH='/home/user/files/test.txt'
hl='/home/user/files' and ll='/test.txt' \- matches single file
.TP
PATH='/home/user/*.txt'
hl="/home/user" and ll='/*.txt' \- matches any file ending with '.txt' in path '/home/user'
.TP
PATH='/home/*/files/??.txt'
hl='/home/*/files' and ll='/??.txt' \- matches all files with two characters and ending with '.txt' in all paths matching '/home/*/files'.
.PP
When in archive mode a path to an existing file or directory is required which should be stored on the tsm server. If path points to an directory all files in it will be archived. See additional options to store directories recursivly.

.SH FILES
File 'dsm.sys' contains information to look up the tsm server. By default it is located at '/opt/tivoli/tsm/client/api/bin64/dsm.sys'.
It should contain at least the required options SERVERNAME, NODENAME and TCPSERVERADDRESS.

.SH BUGS
Please report bugs to <http://github.com/tstibor/ltsm/issues>

.SH SEE ALSO
Github project at <http://github.com/tstibor/ltsm>
